# Edge Handling

In [1]:
import random
import pandas as pd
from faker import Faker
from datetime import datetime

### 1:Database creation and connection

In [2]:
import sqlite3
conn = sqlite3.connect("retail.db")
cursor=conn.cursor()
print("Database Connected")

Database Connected

## 2:Table Creation

In [3]:
customers = pd.read_csv("customers.csv")
products = pd.read_csv("cleaned_products.csv")
orders = pd.read_csv("cleaned_orders.csv")
order_items = pd.read_csv("order_items.csv")

In [4]:
customers.to_sql("customers",conn,if_exists="replace",index=False)

products.to_sql("products",conn,if_exists="replace",index=False)

orders.to_sql("orders",conn,if_exists="replace",index=False)

order_items.to_sql("order_items",conn,if_exists="replace",index=False)

500

## 3:Query run function

In [5]:
def run_query(query):
    return pd.read_sql_query(query,conn)

## Part 5: Edge Case Handling

#### 1:What happens when order_items has an order_id not in orders?

In [8]:
orders = pd.read_csv("cleaned_orders.csv")
order_items = pd.read_csv("order_items.csv")
invalid = order_items[
    ~order_items["order_id"].isin(orders["order_id"])
]
invalid

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_price]
Index: []

#### 2:What happens when discount_percent > 100?

In [10]:
order_items = pd.read_csv("order_items.csv")
df=order_items[order_items["discount_price"]>100]
df

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_price]
Index: []

#### 3:What happens when quantity is 0?

In [11]:
items = pd.read_csv("order_items.csv")
df=items[items["quantity"] == 0]
df

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_price]
Index: []

#### 4:What happens when order_date is in the future?

In [12]:
orders = pd.read_csv("cleaned_orders.csv")
orders["order_date"]=pd.to_datetime(orders["order_date"])
future = orders[orders["order_date"]>pd.Timestamp.today()]
future

Empty DataFrame
Columns: [order_id, customer_id, order_date, status, regions]
Index: []