# Weekly analysis

In [25]:
import random
import pandas as pd
from faker import Faker
from datetime import datetime

### 1:Database creation and connection

In [26]:
import sqlite3
conn = sqlite3.connect("retail.db")
cursor=conn.cursor()
print("Database Connected")

Database Connected

## 2:Table Creation

In [5]:
customers = pd.read_csv("customers.csv")
products = pd.read_csv("cleaned_products.csv")
orders = pd.read_csv("cleaned_orders.csv")
order_items = pd.read_csv("order_items.csv")

In [6]:
customers.to_sql("customers",conn,if_exists="replace",index=False)

products.to_sql("products",conn,if_exists="replace",index=False)

orders.to_sql("orders",conn,if_exists="replace",index=False)

order_items.to_sql("order_items",conn,if_exists="replace",index=False)

500

## 3:Query run function

In [7]:
def run_query(query):
    return pd.read_sql_query(query,conn)

## Part 4: Python + SQL Integration

In [12]:
report_type = input("Enter Report Type (Daily/Weekly/Monthly): ")
start_date = input("Enter Start Date (YYYY-MM-DD): ")
end_date = input("Enter End Date (YYYY-MM-DD): ")

Enter Report Type (Daily/Weekly/Monthly):  weekly
Enter Start Date (YYYY-MM-DD):  2025-01-01
Enter End Date (YYYY-MM-DD):   2025-01-08

##### 1: Total Orders

In [13]:
query = f"""
select count(*) as total_orders
from orders
where date(order_date)
between '{start_date}'and'{end_date}'
"""
total_orders =run_query(query)
print(total_orders)

   total_orders
0             0

##### 2:Total Revenue

In [19]:
query = f"""
select round(sum(quantity*unit_price*(1-discount_price/100.0)),2)as revenue
from order_items oi
join orders o
on oi.order_id=o.order_id
where date(order_date)
between '{start_date}' and '{end_date}'
"""
total_revenue=run_query(query)
total_revenue

  revenue
0    None

##### 3: Unique Customers

In [20]:
query =f"""
select count(distinct customer_id) as unique_customers
from orders
where date(order_date)
between '{start_date}'
and '{end_date}'
"""
unique_cust=run_query(query)
unique_cust

   unique_customers
0                 0

##### 4:Top 3 Products

In [24]:
query=f"""
select p.product_name,sum(oi.quantity) quantity from products p
join order_items oi
on p.product_id=oi.product_id
join orders o
on oi.order_id=o.order_id
where date(order_date)
between '{start_date}'
and'{end_date}'
group by p.product_name
order by quantity DESC
limit 3
"""
top_3_product=run_query(query)
top_3_product

Empty DataFrame
Columns: [Product_name, quantity]
Index: []