## Data cleaning

### Import required libraries

In [2]:
import random
import pandas as pd
from faker import Faker
from datetime import datetime

### 1:Orders data cleaning

In [12]:
df=pd.read_csv("orders.csv")
df.head(3)

   order_id  customer_id           order_date     status regions
0         1        176.0  2026-05-31 19:35:56     PLACED    EAST
1         2        382.0  2026-03-03 08:52:59    SHIPPED    WEST
2         3        259.0  2024-08-30 03:26:15  DELIVERED   NORTH

In [13]:
print(f"Shape:{df.shape}")
print(f"No of rows:{df.shape[0]}")
print(f"No of columns:{df.shape[1]}")

Shape:(500, 5)
No of rows:500
No of columns:5

In [14]:
print("No of null values in each column:")
df.isnull().sum()

No of null values in each column:

order_id        0
customer_id    31
order_date      0
status          0
regions         0
dtype: int64

In [15]:
print("No of duplicate records:")
df[df.duplicated()].sum()

No of duplicate records:

order_id         0
customer_id    0.0
order_date       0
status           0
regions          0
dtype: object

In [16]:
def clean_orders(df):
     df["customer_id"]=df["customer_id"].fillna("unknown")
     df["order_date"]=pd.to_datetime(df["order_date"],format="mixed").dt.strftime("%Y-%m-%d %H:%M:%S")
     return df
df=clean_orders(df)

In [17]:
print("After handling null values:")
df.isnull().sum()

After handling null values:

order_id       0
customer_id    0
order_date     0
status         0
regions        0
dtype: int64

In [18]:
df.to_csv("cleaned_orders.csv", index=False)

### 2:Products data cleaning

In [19]:
df=pd.read_csv("products.csv")

In [20]:
print(f"Shape:{df.shape}")
print(f"No of rows:{df.shape[0]}")
print(f"No of columns:{df.shape[1]}")

Shape:(500, 5)
No of rows:500
No of columns:5

In [21]:
print("No of null values in each column:")
df.isnull().sum()

No of null values in each column:

Product_id      0
Product_name    0
Category        0
Subcategory     0
Cost_price      0
dtype: int64

In [22]:
print("No of duplicate records:")
df[df.duplicated()].sum()

No of duplicate records:

Product_id      0
Product_name    0
Category        0
Subcategory     0
Cost_price      0
dtype: object

In [23]:
def clean_products(df):
    df["Product_name"]=df["Product_name"].str.strip()
    df["Product_name"]=df["Product_name"].str.title()
    return df
df=clean_products(df)

In [24]:
df.to_csv("cleaned_products.csv" ,index=False)

### 3:Customers data cleaning

In [40]:
df=pd.read_csv("customers.csv")
df.head(5)

,customer_id,customer_name,email,registration_date,customer_type
0,1,Betty Evans,carpenteraaron@example.com,2025-02-17,PREMIUM
1,2,Timothy Marks,wmiller@example.org,2022-10-09,REGULAR
2,3,Gary Cooper,rschmidt@example.net,2026-05-19,REGULAR
3,4,Lauren Mathis,dyerjose@example.net,2024-11-25,REGULAR
4,5,William Mcdonald DDS,hgates@example.org,2023-08-31,PREMIUM

In [41]:
print(f"Shape:{df.shape}")
print(f"No of rows:{df.shape[0]}")
print(f"No of columns:{df.shape[1]}")

Shape:(500, 5)
No of rows:500
No of columns:5

In [42]:
print("No of null values in each column:")
df.isnull().sum()

No of null values in each column:

customer_id          0
customer_name        0
email                0
registration_date    0
customer_type        0
dtype: int64

In [43]:
print("No of duplicate records:")
df[df.duplicated()].sum()

No of duplicate records:

customer_id          0
customer_name        0
email                0
registration_date    0
customer_type        0
dtype: object

In [44]:
def validate_emails(df):
    invalid_emails=df[
        ~df["email"].str.contains("@") |
        ~df["email"].str.contains(".com", regex=False)
]
    return invalid_emails[["customer_id", "email"]]

In [45]:
validate_emails(df)

     customer_id                    email
1              2      wmiller@example.org
2              3     rschmidt@example.net
3              4     dyerjose@example.net
4              5       hgates@example.org
5              6       judy33@example.org
..           ...                      ...
491          492    karenhuff@example.org
492          493   alimichael@example.net
494          495   aaronsmith@example.org
497          498  adrianbrown@example.org
498          499     tamara69@example.net

[336 rows x 2 columns]

In [47]:
df.to_csv("cleaned_customers.csv")

### 4:Invalid orders

In [31]:
orders=pd.read_csv("orders.csv")
order_items=pd.read_csv("order_items.csv")

In [32]:
def check_referential_integrity(order_items,orders):
    invalid_orders = order_items[
        ~order_items["order_id"].isin(orders["order_id"])
    ]
    return invalid_orders
    
df=check_referential_integrity(order_items,orders)
df

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_price]
Index: []

In [39]:
order_items.to_csv("cleaned_order_items.csv")